### ISSUE TITLE
Pls update the ember-cli version

### ISSUE THREAD

**Issue by govidat** [danlynn/ember-cli#1]
Thanks a lot for your ember-cli image. Can you pls update the ember-cli version to the latest version 1.13.13?

**Comment by danlynn** [comment]
Thanks for letting me know that I had fallen behind the current ember-cli version.

The Image has been updated to 1.13.13.

Also updated node to 4.2.3, npm to 2.11.0, bower to 1.7.1, and phantomjs to 1.9.19.

Notice that I updated the README to include a note about fixing an fs.inotify.max_user_watches sysctl limits issue that may occur on projects like ember which have lots of files.
