### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by iamdtang** [danlynn/ember-cli#10]
Everything works, but I noticed that for larger projects the initial `ember serve` and file watching is really slow. Making 1 change in a JS file causes the livereload to take about a minute. Is this just the nature of file watching through the container?

**Comment by danlynn** [comment]
Volume-izing the bower_components and node_modules directories can provide a dramatic improvement in build times.  I intend to update the README with volume-izing tips soon.

Switching to using NFS to share your project dir can also yield performance improvements - especially if using docker-machine and VirtualBox.  I show how to do this here: 

	https://github.com/danlynn/ember-cli/wiki/Setup-NFS-Shares-on-VirtualBox

**Comment by iamdtang** [comment]
Thanks Dan!

**Comment by pcambra** [comment]
I need to explore more about it but probably this would help https://github.com/EugenMayer/docker-sync

We also mount the tmp folder in a tmpfs in our docker compose:

`- app_tmp:/app/tmp`

```
volumes:
  app_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
```

I'd suggest maybe leave this open to get more information and maybe produce docs about this?
