### ISSUE TITLE
Ember-cli version needs to be updated

### ISSUE THREAD

**Issue by govidat** [danlynn/ember-cli#2]
Hello, 
There is a jquery related bug in using this image in ember-cli version 1.13.13. 

The recommendation is to upgrade the cli version. Details in ; 
https://github.com/ember-cli/ember-cli/issues/5365#issuecomment-172152919

**Comment by danlynn** [comment]
Updated to 1.13.14.  See https://hub.docker.com/r/danlynn/ember-cli/
