### ISSUE TITLE
Add open source licence

### ISSUE THREAD

**Issue by karl-cardenas-coding** [danlynn/ember-cli#24]
Hi there. First off all, thank you for maintaining an Ember.js image for the community, we really appreciate it.  I was wondering if you could by any chance add a licence to the image repo. The reason being that some us (in the corporate world) can't use this image due to legal reasons. The reason being it's missing an open source licence. Any chance we can add a licence to this repo?

**Comment by danlynn** [comment]
Added MIT license.  Have a nice day!
